fix deno running infinite loop
stylus/stylus pull request #2745
Opened 2022-12-27 03:22 UTC by vixalien

**What**:

This PR allows `stylus` to work on `deno`, an alternative to Node.JS

**Why**:

Deno is gaining traction, and I personally use stylus, so I wanted to contrinue using stylus with Deno (after I switched to it from Node)

**How**:

The fix is two-steps:

1. Use `Object.setPrototypeOf` instead of the deprecated `__proto__` (which Deno doesn't support)
2. Fix a call in the `boolean` node that called the `Boolean` function, causing deno to run into an infinite loop as it was calling the constructor from the constructor in a recursive way.

**I THINK THIS IS OKAY, BUT PLEASE VERIFY**

**Checklist**:

- [ ] Documentation N/A
- [ ] Unit Tests N/A
- [x] Code complete
- [ ] Changelog

May I recommend moving to ES6 classes (would help) in the future, instead of modifying the prototype chain manually as this results in code reliability & performance issues.

2022-12-27 03:24 UTC, vixalien commented
I forgot to add that this is a very minor change (in face of the user) as the API is unmodified and everything (including tests) works exactly as expected.

2023-04-05 16:25 UTC, vixalien commented
anyone?

2023-04-06 02:00 UTC, iChenLei commented
Can you add github action ci for stylus with deno environment ?

2023-08-11 09:01 UTC, vixalien commented
@iChenLei  ptal

2023-08-11 10:57 UTC, iChenLei requested changes

2023-08-11 10:57 UTC, iChenLei commented on lib/nodes/object.js
> +globalThis.Object.setPrototypeOf(Object.prototype, Node.prototype);
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility See `globalThis ` compatibility

2023-08-11 12:11 UTC, vixalien commented
@iChenLei fixed

2023-08-13 10:56 UTC, vixalien commented
@iChenLei I believe stylus's dependencies do not support older versions of node anymore.

In the logs you can see `mocha` says

```
unsupported engine for mocha@9.2.2: wanted: {"node":">= 12.0.0"} (current: {"node":"10.24.1","npm":"6.14.12"})
```

also `@adobe/css-tools` causes the test to fail since it uses an optional chaining operator (`?.`) which works on node v14+.

The `mocha` warning can be ignored. but the `@adobe/css-tools` one cannot be ignored. we'll need to use an older version of this package if supporting older versions of node is a must.

2023-08-14 07:23 UTC, vixalien commented
@iChenLei ptal

2023-08-14 07:39 UTC, iChenLei commented
I have a question: why not directly convert `function` into `class` (only needing [Node.js v4+](https://node.green/#ES2015-functions-class)), instead of using `setPrototypeOf`? Plus, you don't need to care about the issues with `@adobe/css-tools`.

2023-08-14 07:40 UTC, iChenLei reviewed
I have a question: why not directly convert `function` into `class` (only needing [Node.js v4+](https://node.green/#ES2015-functions-class)), instead of using `setPrototypeOf`? Plus, you don't need to care about the issues with `@adobe/css-tools`.

2023-08-14 07:53 UTC, vixalien commented
that can be done yes, I was surprised why stylus does this too. since it'll be a huge change, I'll be working on a separate PR. stay tuned

2023-08-14 11:31 UTC, vixalien commented
@iChenLei made a PR for Classes in #2813

2023-08-14 11:48 UTC, iChenLei commented
So, can we close thise PR ?

2023-08-14 11:50 UTC, vixalien commented
yes.

2023-08-14 11:50 UTC, closed without merging